version: &version 2.1


####################
# Templates
####################

executors:
  scala_212:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SCALA_VERSION: 2.12.10
  scala_211:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SCALA_VERSION: 2.11.12

commands:
  build:
    parameters:
      build-steps:
        description: "build steps"
        type: steps
        default: []
    steps:
      - checkout
      - run:
          command: |
            sbt clean "project $TEST_PROJECT" scalastyle test:scalastyle test


####################
# Jobs
####################

jobs:
  avro_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzurAvro
    steps:
      - build
  core_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzurCore
    steps:
      - build
  examples_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzurExamples
    steps:
      - build
  schemas_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzurSchemas
    steps:
      - build
  scio_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzurScio
    steps:
      - build
      
  avro_211:
    executor: scala_211
    environment:
      TEST_PROJECT=elitzurAvro
    steps:
      - build
  core_211:
    executor: scala_211
    environment:
      TEST_PROJECT=elitzurCore
    steps:
      - build
  examples_211:
    executor: scala_211
    environment:
      TEST_PROJECT=elitzurExamples
    steps:
      - build
  schemas_211:
    executor: scala_211
    environment:
      TEST_PROJECT=elitzurSchemas
    steps:
      - build
  scio_211:
    executor: scala_211
    environment:
      TEST_PROJECT=elitzurScio
    steps:
      - build


####################
# Workflows
####################

workflows:
  version: *version

  # Per commit build
  build:
    jobs:
      - avro_212
      - core_212
      - examples_212
      - schemas_212
      - scio_212

      - avro_211
      - core_211
      - examples_211
      - schemas_211
      - scio_211
